#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : beautifulsoup4
Version  : 4.8.2
Release  : 61
URL      : https://files.pythonhosted.org/packages/52/ba/0e121661f529e7f456e903bf5c4d255b8051d8ce2b5e629c5212efe4c3f1/beautifulsoup4-4.8.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/52/ba/0e121661f529e7f456e903bf5c4d255b8051d8ce2b5e629c5212efe4c3f1/beautifulsoup4-4.8.2.tar.gz
Summary  : Screen-scraping library
Group    : Development/Tools
License  : MIT
Requires: beautifulsoup4-license = %{version}-%{release}
Requires: beautifulsoup4-python = %{version}-%{release}
Requires: beautifulsoup4-python3 = %{version}-%{release}
Requires: html5lib
Requires: lxml
Requires: soupsieve
BuildRequires : buildreq-distutils3
BuildRequires : html5lib
BuildRequires : lxml
BuildRequires : py
BuildRequires : pytest
BuildRequires : soupsieve

%description
Beautiful Soup is a Python package for parsing HTML and XML documents.

%package license
Summary: license components for the beautifulsoup4 package.
Group: Default

%description license
license components for the beautifulsoup4 package.


%package python
Summary: python components for the beautifulsoup4 package.
Group: Default
Requires: beautifulsoup4-python3 = %{version}-%{release}

%description python
python components for the beautifulsoup4 package.


%package python3
Summary: python3 components for the beautifulsoup4 package.
Group: Default
Requires: python3-core
Provides: pypi(beautifulsoup4)

%description python3
python3 components for the beautifulsoup4 package.


%prep
%setup -q -n beautifulsoup4-4.8.2
cd %{_builddir}/beautifulsoup4-4.8.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582850132
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/beautifulsoup4
cp %{_builddir}/beautifulsoup4-4.8.2/COPYING.txt %{buildroot}/usr/share/package-licenses/beautifulsoup4/96063bf55c010062c01e3792177b9fabda28eb82
cp %{_builddir}/beautifulsoup4-4.8.2/LICENSE %{buildroot}/usr/share/package-licenses/beautifulsoup4/1295b7c053fbc5d5bfe3b7aac318703d01d1e227
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/beautifulsoup4/1295b7c053fbc5d5bfe3b7aac318703d01d1e227
/usr/share/package-licenses/beautifulsoup4/96063bf55c010062c01e3792177b9fabda28eb82

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
