#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : beautifulsoup4
Version  : 4.6.3
Release  : 50
URL      : https://files.pythonhosted.org/packages/88/df/86bffad6309f74f3ff85ea69344a078fc30003270c8df6894fca7a3c72ff/beautifulsoup4-4.6.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/88/df/86bffad6309f74f3ff85ea69344a078fc30003270c8df6894fca7a3c72ff/beautifulsoup4-4.6.3.tar.gz
Summary  : Screen-scraping library
Group    : Development/Tools
License  : MIT
Requires: beautifulsoup4-python3
Requires: beautifulsoup4-license
Requires: beautifulsoup4-python
Requires: html5lib
Requires: lxml
BuildRequires : buildreq-distutils3
BuildRequires : py
BuildRequires : pytest

%description
from web pages. It sits atop an HTML or XML parser, providing Pythonic
        idioms for iterating, searching, and modifying the parse tree.
        
        # Quick start
        
        ```
          >>> from bs4 import BeautifulSoup
          >>> soup = BeautifulSoup("<p>Some<b>bad<i>HTML")
          >>> print soup.prettify()
          <html>
           <body>
            <p>
             Some
             <b>
              bad
              <i>
               HTML
              </i>
             </b>
            </p>
           </body>
          </html>
          >>> soup.find(text="bad")
          u'bad'
        
          >>> soup.i
          <i>HTML</i>
        
          >>> soup = BeautifulSoup("<tag1>Some<tag2/>bad<tag3>XML", "xml")
          >>> print soup.prettify()
          <?xml version="1.0" encoding="utf-8">
          <tag1>
           Some
           <tag2 />
           bad
           <tag3>
            XML
           </tag3>
          </tag1>
        ```

%package license
Summary: license components for the beautifulsoup4 package.
Group: Default

%description license
license components for the beautifulsoup4 package.


%package python
Summary: python components for the beautifulsoup4 package.
Group: Default
Requires: beautifulsoup4-python3

%description python
python components for the beautifulsoup4 package.


%package python3
Summary: python3 components for the beautifulsoup4 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the beautifulsoup4 package.


%prep
%setup -q -n beautifulsoup4-4.6.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534166532
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/beautifulsoup4
cp COPYING.txt %{buildroot}/usr/share/doc/beautifulsoup4/COPYING.txt
cp LICENSE %{buildroot}/usr/share/doc/beautifulsoup4/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/beautifulsoup4/COPYING.txt
/usr/share/doc/beautifulsoup4/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
